# redis
athena:
  # 使用redis
  redis:
    ip: 127.0.0.1
    port: 6379
    time_out: 500
    max_connection: 8
    max_idle: 8
    min_idle: 0
    max_wait_time: -1
    test_onBorrow: true

# druid
spring:
  datasource:
    name: athena
    url: jdbc:mysql://127.0.0.1:3306/athena?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  aop:
    proxy-target-class: true

mybatis:
  mapperLocations: classpath:mybatis/*.xml
  typeAliasesPackage: com.athena.entity


logging:
  config: classpath:log.xml
  path: "/Users/Hero/logs"



